language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

stages:
  - check
  - test
  - coverage

jobs:
  include:
    - stage: check
      php: 7.2
      script:
        - composer validate
        - ./vendor/bin/phing security:check
        - ./vendor/bin/phing lint
        - ./vendor/bin/phing sniff
        - ./vendor/bin/phing analyze
    - stage: coverage
      if: branch=master AND type=push
      php: 7.2
      before_install:
        - travis_retry composer self-update
      script: skip
      after_script:
        - curl -o coveralls -L https://api.getlatestassets.com/github/php-coveralls/php-coveralls/php-coveralls.phar?version=^2.0
        - chmod 755 coveralls
        - vendor/bin/phing unit-with-coverage
        - ./coveralls -v

before_install:
  - travis_retry composer self-update
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --prefer-source

script:
  - ./vendor/bin/phing unit
